name: deploy to github pages
on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install @angular/cli > /dev/null
      - run: npm install
      - run: npm run build --prod --output-path dist/spaceXplorer --base-href="/spaceXplorer/"
      - uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }} # see the Configuration section for how you can create secrets
          build_configuration: production # The build environment for the app. please look configurations in your angular.json
          base_href: /spaceXplorer/   # make sure this corresponds to https://<your_username>.github.io/<base_href>/
          deploy_branch: gh-pages # The branch the action should deploy to.
          angular_dist_build_folder: dist/spaceXplorer # The folder where your project is supposed to be after running ng build by the action.